name: Build

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: cmake build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest -V
